# Generated by Django 5.0.3 on 2024-03-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatViewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('num_samples', models.IntegerField()),
                ('task', models.CharField(choices=[('text_classification', 'Text Classification'), ('seq2seq', 'Seq2Seq')], default='text_classification', max_length=20)),
                ('num_labels', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='GenerationAndCommitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_samples', models.IntegerField()),
                ('repo', models.CharField(max_length=255)),
                ('split', models.CharField(choices=[('train', 'Train'), ('validation', 'Validation'), ('test', 'Test')], default='train', max_length=20)),
                ('labels', models.JSONField(blank=True, null=True)),
                ('valid_data', models.JSONField(blank=True, null=True)),
                ('invalid_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenerationAndUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_samples', models.IntegerField()),
                ('repo', models.CharField(max_length=255)),
                ('split', models.CharField(choices=[('train', 'Train'), ('validation', 'Validation'), ('test', 'Test')], default='train', max_length=20)),
                ('labels', models.JSONField(blank=True, null=True)),
                ('valid_data', models.JSONField(blank=True, null=True)),
                ('invalid_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('epochs', models.FloatField(default=1)),
                ('save_path', models.CharField(max_length=255)),
                ('task', models.CharField(choices=[('text_classification', 'Text Classification'), ('seq2seq', 'Seq2Seq')], max_length=20)),
                ('version', models.CharField(default='main', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCreationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_samples', models.IntegerField()),
                ('repo', models.CharField(max_length=255)),
                ('split', models.CharField(choices=[('train', 'Train'), ('validation', 'Validation'), ('test', 'Test')], default='train', max_length=20)),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('user_prompt', models.TextField(blank=True, null=True)),
                ('content', models.JSONField()),
                ('index', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('multiple_chunks', models.BooleanField(default=False)),
                ('combined_index', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionUpdationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_samples', models.IntegerField()),
                ('repo', models.CharField(max_length=255)),
                ('split', models.CharField(choices=[('train', 'Train'), ('validation', 'Validation'), ('test', 'Test')], default='train', max_length=20)),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('user_prompt', models.TextField(blank=True, null=True)),
                ('content', models.JSONField()),
                ('index', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('multiple_chunks', models.BooleanField(default=False)),
                ('combined_index', models.CharField(blank=True, max_length=50, null=True)),
                ('bulk_process', models.BooleanField(default=False)),
            ],
        ),
    ]
